#!/usr/bin/env ruby

=begin

Print the numbers 1..100
For multiples of 3, print “Fizz” instead of the number
For multiples of 5, print “Buzz” instead of the number
For multiples of 3 and 5, print “FizzBuzz” instead of the number

=end

    1.upto(100) do |i|
      if i % 5 == 0 and i % 3 == 0
        puts "FizzBuzz"
      elsif i % 5 == 0
        puts "Buzz"
      elsif i % 3 == 0
        puts "Fizz"
      else
        puts i
      end
    end
